site_name: My Frontend Guide
site_url: https://stiename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  # icon:
  #   logo: fontawesome/brands/twitch
  logo: assets/code-solid-full.svg
  favicon: assets/code-solid-full.svg
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark mode
      primary: teal
      accent: deep orange
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Light mode
      primary: indigo
      accent: teal
  # features for navigation and search
  features:
    - navigation.instant
    - navigation.instant.progress
    # - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    # - content.code.select
    - content.tooltips

plugins:
  - search
  - tags:
      tags_file: tags.md
  - glightbox
  - blog:
      enabled: true
      blog_toc: true
      # post_date_format: short
      # post_date_format: medium
      # post_date_format: long
      post_date_format: full
      # post_excerpt_separator: <!-- more -->
      # post_readtime: false
      # archive: false
      # archive_name: Archive Demos
      # categories: false
      # categories_name: Categories Demos
      # categories_sort_reverse: true
      # categories_url_format: "category/{slug}"
      # categories_pagination: false
      # categories_pagination_per_page: 1
      categories_toc: true
      authors_file: "blog/.authors.yml"
      # authors: false
      # authors_profiles: true

nav:
  - Home: index.md
  - React Docs: 
    - 0.List of Content: react/react-list.md
    - 1.Introduction to React: react/1.Introduction to React.md
    - 2.Setting Up the Environment: react/2.Setting Up the Environment.md
    - 3.Understanding jsx: react/3.Understanding jsx.md
    - 4.React Components: react/4.React Components.md
    - 5.State & Data Management: react/5.React State and Data Management.md
    - 6.Handling Events in React: react/6.Handling Events in React.md
    - 7.React Hooks: react/7.React Hooks.md
    - Important Keywords: react/Important Keywords.md
  - TypeScript Docs:
    - 0.List of Content: ts/ts-list.md
    - 1.Introduction to TypeScript: ts/1.Introduction to TS.md
    - 2.Basic Types and Type Inference, Annotations & Assertions: ts/2.Basic Types.md
    - 3.Functions, Objects and Classes in TypeScript: ts/3.Functions Objects and Classes.md
    - 4.Advanced Types: ts/4.Advanced Types.md
    - 5.Generics: ts/5.Generics.md
    - 6.Modules and Namespaces: ts/6.Modules and Namespaces.md
    - 7.Declaration Files: ts/7.Declaration Files.md
    - 8.TypeScript and JavaScript Interop: ts/8.TypeScript and JavaScript Interop.md
    - 9.Tooling & Configuration: ts/9.Tooling & Configuration.md
    - 10.Working with Third-Party Libraries: ts/10.Working with Third-Party Libraries.md
    - 11.React + TypeScript: ts/11.React + TypeScript.md
    - 12.Node.js + TypeScript: ts/12.Node.js + TypeScript.md
    - 13.Testing in TypeScript: ts/13.Testing in TypeScript.md
    - 14.Best Practices: ts/14.Best Practices.md
    - 15.Troubleshooting and Debugging: ts/15.Troubleshooting and Debugging.md
    - 16.Advanced Topics: ts/16.Advanced Topics.md
    - 17.Appendix: ts/17.Appendix.md
  # - Blog:
    # - blog/index.md
  # - Tags: tags.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.blocks.caption

extra:
  social:
    - icon: material/folder-account
      link: https://souravkumardash.vercel.app
    - icon: material/linkedin
      link: https://www.linkedin.com/in/sourav183
    - icon: simple/github
      link: https://github.com/Captain-Rengoku

copyright: Copyright &copy; 2024 S.Kumar
