authors:
  skumar:
    name: S.Kumar
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/130641136?s=400&u=8f7614a4db52356ea9ddd7269de86da3487dae6d&v=4
    url: https://github.com/Captain-Rengoku
  # alexvoss:
  #   name: Alex Voss
  #   description: Solutions Architect
  #   avatar: https://avatars.githubusercontent.com/u/4134224
  #   url: https://github.com/alexvoss
  # katharinalisalin:
  #   name: Kathi
  #   description: Communications
  #   avatar: https://avatars.githubusercontent.com/u/105352741
  #   url: https://github.com/katharinalisalin